name: Build

on:
  schedule:
    - cron: 0 0 * * FRI
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v21
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-node@v1
        with:
          node-version: 17

      